# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stationtypes', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hydrology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estacion', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('altura', models.CharField(blank=True, max_length=10, null=True)),
                ('max', models.CharField(blank=True, max_length=10, null=True)),
                ('med', models.CharField(blank=True, max_length=10, null=True)),
                ('min', models.CharField(blank=True, max_length=10, null=True)),
                ('p10', models.CharField(blank=True, max_length=10, null=True)),
                ('p50', models.CharField(blank=True, max_length=10, null=True)),
                ('p90', models.CharField(blank=True, max_length=10, null=True)),
                ('id_estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationtypes.StationType')),
            ],
            options={
                'verbose_name': 'Hidrolog\xeda',
                'verbose_name_plural': 'Hidrologias',
            },
        ),
    ]
