# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0006_auto_20170114_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=240, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Estacion',
                'verbose_name_plural': 'Estaciones',
            },
        ),
    ]
