# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-10 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stationtypes', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='fktypestation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stationtypes.StationType'),
            preserve_default=False,
        ),
    ]
