# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('id_dpto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Department')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
    ]
