# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
        ('climatologies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='climatology',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stations.Station'),
            preserve_default=False,
        ),
    ]
