# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lon_gra',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
