# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20170111_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='elev',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat_gra',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat_min',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lon_gra',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lon_min',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=1000, null=True),
        ),
    ]
