# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('locations', '0005_auto_20170112_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='id_dpto',
        ),
        migrations.AddField(
            model_name='location',
            name='id_ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cities.City'),
            preserve_default=False,
        ),
    ]
